"set t_Co=256
set background=dark
syntax on
set number
set hlsearch
set nocompatible
set ai
set history=700
set wildmenu
set ruler
set cmdheight=1
set hid
set ignorecase
set smartcase
set incsearch
set lazyredraw
set magic
set t_vb =
set tm=500
set expandtab
set smarttab
set shiftwidth=4
set tabstop=4
set lbr
set tw=500
set wrap
set noswapfile
set laststatus=2
set autoread
filetype indent on

function! FixLastSpellingError()
    normal! mm[s1z=`m
endfunction
nnoremap <leader>sp :call FixLastSpellingError()<CR>

iabbrev teh the
iabbrev iot in order to
iabbrev doc documentation

augroup custom_html
    autocmd!
    autocmd FileType html nnoremap <buffer> <localleader>f Vatzf
augroup end

augroup custom_javascript
    autocmd!
    autocmd FileType javascript iabbrev <buffer>ffor for(var i = 0; i < lessthan; i++){<Enter>}<Esc>k0f<wviw
augroup end

augroup custom_ruby
    autocmd!
    autocmd FileType ruby iabbrev <buffer>iff if<Enter>end<Enter><Esc>kkA
    autocmd FileType ruby iabbrev <buffer>ife if<Enter>else<Enter>end<Enter><Esc>kkkA
augroup end

augroup custom_mixed
    autocmd!
    autocmd FileType php,cpp,javascript,c iabbrev <buffer>iff if () {<Enter>}<Esc>bbf)i
    autocmd FileType php,cpp,javascript,c iabbrev <buffer>ife if () {<Enter>} else {<Enter>}<Esc>kk0f)i
    autocmd FileType php iabbrev <buffer>ffor for($i = 0; $i < lessthan; $i++){<Enter>}<Esc>k0f<wviw<left>
    autocmd FileType javascript,php nnoremap<buffer><localleader>c I//<esc>j
    autocmd FileType python,ruby nnoremap<buffer><localleader>c I#<esc>j
augroup end

onoremap p i(
onoremap in :<c-u>normal! f(vi(<cr>
onoremap il :<c-u>normal! F)vi(<cr>
onoremap fn :<c-u>normal! 0f(hviw<CR>
onoremap ih :<c-u>execute "normal! ?^==\\+$\r:nohlsearch\rkvg_"<cr>

inoremap <c-\>e else {<Enter>}<Esc>O
inoremap jk <esc>
nnoremap <leader>" viw<esc>a"<esc>hbi"<esc>lel
nnoremap <leader>' viw<esc>a'<esc>hbi'<esc>lel
vnoremap <leader>: <esc>`<i"<esc>`>la"<esc>
vnoremap <leader>; <esc>`<i'<esc>`>la'<esc>
nnoremap <leader>ev :vsplit $MYVIMRC<cr>
nnoremap <silent> <c-k> :wincmd k<CR>
nnoremap <silent> <c-j> :wincmd j<CR>
nnoremap <silent> <c-h> :wincmd h<CR>
nnoremap <silent> <c-l> :wincmd l<CR>
noremap <silent><leader>2 :NumbersToggle<CR>
noremap <silent><leader>a :spellr<CR>
noremap <silent><leader>b :TagbarToggle<CR>
noremap <silent><leader>q :bp<bar>sp<bar>bn<bar>bd<CR>
noremap <silent><leader>r :AirlineRefresh<CR>
noremap <silent><leader>t :tselect<CR>
noremap <leader>w :StripWhitespace<CR>
nnoremap <leader>sv :source %<CR>

"Pathogen
execute pathogen#infect()

noremap <silent><C-n> :NERDTreeToggle<CR>

"setglobal spell spelllang=en_us
"set spell

color jellybeans

if !exists('g:airline_symbols')
    let g:airline_symbols = {}
endif

" unicode symbols
let g:airline_left_sep = '»'
let g:airline_left_sep = '▶'
let g:airline_right_sep = '«'
let g:airline_right_sep = '◀'
let g:airline_symbols.crypt = '🔒'
let g:airline_symbols.linenr = '␊'
let g:airline_symbols.linenr = '␤'
let g:airline_symbols.linenr = '¶'
let g:airline_symbols.maxlinenr = '☰'
let g:airline_symbols.maxlinenr = ''
let g:airline_symbols.branch = '⎇'
let g:airline_symbols.paste = 'ρ'
let g:airline_symbols.paste = 'Þ'
let g:airline_symbols.paste = '∥'
let g:airline_symbols.spell = 'Ꞩ'
let g:airline_symbols.notexists = '∄'
let g:airline_symbols.whitespace = 'Ξ'
let g:syntastic_always_populate_loc_list = 1
let g:syntastic_auto_loc_list = 1
let g:syntastic_check_on_open = 1
let g:syntastic_check_on_wq = 0

