" Sets {{{ -----------------------

set t_Co=256
set background=dark
set foldlevelstart=0
syntax on
set number
set hlsearch
set nocompatible
set ai
set history=700
set ruler
set cmdheight=1
set hid
set ignorecase
set smartcase
set incsearch
set expandtab
set smarttab
set shiftwidth=4
set tabstop=4
set lbr
set tw=500
set wrap
set noswapfile
set laststatus=2
set autoread
filetype indent on

" }}}
" Autocmds {{{ ---------------------------------------------------

augroup custom_vim
    autocmd!
    autocmd FileType vim setlocal foldmethod=marker
augroup end

augroup custom_html
    autocmd!
    autocmd FileType html nnoremap <buffer> <localleader>f Vatzf
augroup end

augroup custom_javascript
    autocmd!
    autocmd FileType javascript iabbrev <buffer>ffor for(var i = 0; i < lessthan; i++){<Enter>}<Esc>k0f<wviw
augroup end

augroup custom_ruby
    autocmd!
    autocmd FileType ruby iabbrev <buffer>iff if<Enter>end<Enter><Esc>kkA
    autocmd FileType ruby iabbrev <buffer>ife if<Enter>else<Enter>end<Enter><Esc>kkkA
augroup end

augroup custom_mixed
    autocmd!
    autocmd FileType php,cpp,javascript,c iabbrev <buffer>iff if () {<Enter>}<Esc>bbf)i
    autocmd FileType php,cpp,javascript,c iabbrev <buffer>ife if () {<Enter>} else {<Enter>}<Esc>kk0f)i
    autocmd FileType php iabbrev <buffer>ffor for($i = 0; $i < lessthan; $i++){<Enter>}<Esc>k0f<wviw<left>
    autocmd FileType javascript,php nnoremap<buffer><localleader>c I//<esc>j
    autocmd FileType python,ruby nnoremap<buffer><localleader>c I#<esc>j
augroup end

" }}}
" Mappings {{{ -------------------------------------------------------

onoremap p i(
onoremap in :<c-u>normal! f(vi(<cr>
onoremap il :<c-u>normal! F)vi(<cr>
onoremap fn :<c-u>normal! 0f(hviw<CR>
onoremap ih :<c-u>execute "normal! ?^==\\+$\r:nohlsearch\rkvg_"<cr>
inoremap <c-\>e else {<Enter>}<Esc>O
inoremap jk <esc>
nnoremap <leader>" viw<esc>a"<esc>hbi"<esc>lel
nnoremap <leader>' viw<esc>a'<esc>hbi'<esc>lel
vnoremap <leader>: <esc>`<i"<esc>`>la"<esc>
vnoremap <leader>; <esc>`<i'<esc>`>la'<esc>
nnoremap <leader>ev :vsplit $MYVIMRC<cr>
nnoremap <silent> <c-k> :wincmd k<CR>
nnoremap <silent> <c-j> :wincmd j<CR>
nnoremap <silent> <c-h> :wincmd h<CR>
nnoremap <silent> <c-l> :wincmd l<CR>
nnoremap <leader>vv :e $MYVIMRC<cr>
noremap <silent><leader>2 :NumbersToggle<CR>
noremap <silent><leader>a :spellr<CR>
noremap <silent><leader>b :TagbarToggle<CR>
nnoremap <silent><leader>g :Gst<cr>
nnoremap <leader>+ 10<c-w>+
nnoremap <leader>> 10<c-w>>
nnoremap <leader>< 10<c-w><
noremap <silent><leader>q :bp<bar>sp<bar>bn<bar>bd<CR>
noremap <silent><leader>r :AirlineRefresh<CR>
noremap <silent><leader>t :tselect<CR>
noremap <leader>w :StripWhitespace<CR>
nnoremap <leader>sv :source %<CR>
nnoremap <leader>o O<esc>jo<esc>k
noremap <silent><C-n> :NERDTreeToggle<CR>
nnoremap <leader>sp mm[s1z=`m

" }}}
" Abbreviations {{{ ----------

iabbrev teh the
iabbrev iot in order to
iabbrev doc documentation

" }}}
" Status Line {{{ -----------------

set statusline=%r
set statusline+=%.40f
set statusline+=\ ->\ %y
set statusline+=%m
set statusline+=\ \ Buffer:[%n]
set statusline+=%=
set statusline+=%l
set statusline+=/
set statusline+=%L

" }}}
execute pathogen#infect()
color jellybeans
