(provide 'my-packages)

(require 'package)
(add-to-list 'package-archives '("melpa" . "https://melpa.org/packages/") t)
(require 'use-package-ensure)
(setq use-package-always-ensure t)
(setq use-package-verbose t)

(require 'my-lsp)
(require 'my-vertico)
(require 'my-langs)
(require 'my-ui)
(require 'my-corfu)
(require 'my-gpt)
(require 'my-term)
(require 'my-git)
(require 'my-search)
