(provide 'my-modules)

(require 'my-conf)
(require 'my-defuns)

(require 'my-elpaca)
;; (require 'my-use-package)

;; (require 'my-evil)

(require 'my-vertico)
(require 'my-term)
(require 'my-langs)
(require 'my-prettier)
(require 'my-which-key)
(require 'my-buffers)
(require 'my-windows)
(require 'my-project)
(require 'my-git)
(require 'my-org)
(require 'my-eglot)
(require 'my-search)
(require 'my-tree-sitter)
(require 'my-theme)
(require 'my-modeline)
(require 'my-hooks)
(require 'my-keys)
(require 'my-notes)
