colorscheme red-phoenix

# define-command -docstring "Open file with all git files as options" git-files %{
#     prompt -menu -shell-script-candidates %{ git ls-files } "Open Git File: " %{ e %val{text} }
# }
# alias global E git-files

# line numbers if we want them
# add-highlighter global/ number-lines -hlcursor

# set ruby-specific settings
hook global WinSetOption filetype=(ruby) %{
    set-option buffer indentwidth 2
    set-option buffer softtabstop 2
}

# after typing k, check if the preceding char was j.
# we use jk to exit insert mode instead of <esc>.
# Use \ in normal mode if needing to type jk into the buffer.
hook global InsertChar k %{ try %{
    exec -draft hH <a-k>jk<ret> d
    exec <esc>
}}

# Tmux helpers for splitting screens and opening file pickers
# define-command -docstring "Create new tmux terminal to the right containing new fzf file picker." vertical-split %{
#     tmux-terminal-horizontal ff
# }
# 
# alias global vs vertical-split
# 
# define-command -docstring "Create new tmux terminal below containing new fzf file picker." horizontal-split %{
#     tmux-terminal-vertical ff
# }
# 
# unalias global sp spell
# alias global sp horizontal-split

# PRETTIER!
# hook global BufWritePost .*[.]js %{
#    exec -draft gg%|kak<minus>prettier<space><c-r>%<ret>
# }
