(setq custom-file (concat user-emacs-directory "custom.el"))
(setq gc-cons-threshold (* 60 1000 1000))

(add-to-list 'load-path (concat user-emacs-directory "modules"))

(require 'my-conf)
(require 'my-buffers)
(require 'my-defun)
(require 'my-keys)
(require 'my-general)
(require 'my-hooks)
(require 'my-use-package)
(require 'my-evil)
(require 'my-git)
(require 'my-vertico)
(require 'my-lsp)
(require 'my-org)
(require 'my-theme)
(require 'my-vterm)
(require 'my-modeline)
(require 'my-langs)
(require 'my-company)
(require 'my-completion)
(require 'my-help)
(require 'my-treesitter)
(require 'my-dired)
(require 'my-ui)
(require 'my-navigation)
(require 'my-system)
;; (require 'my-exwm)

(setq gc-cons-threshold 100000000)
(setq read-process-output-max (* 1024 1024)) ;; 1mb
