#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

# main bspwm configuration is elisp, found in bspwm.el
# emacs --script ~/dot/.config/emacs/scripts/bspwm.el &

# polybar
# ~/dot/.config/polybar/launch.sh &

bspc monitor eDP-1 -d 9
bspc monitor HDMI-1-0 -d 1 2 3 4 5 6 7 8

bspc config focused_border_color '#7A619A'
bspc config presel_feedback_color '#6C5689'
bspc config border_width 1
bspc config window_gap 20
bspc config split_ratio 0.5
bspc config focus_follows_pointer false
