#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

xrandr --output eDP-1 --mode 1920x1080 --brightness 1 --output HDMI-1-0 --mode 2560x1440 --primary --right-of eDP-1
feh --bg-scale ~/dot/wallpaper/road.jpg

bspc monitor eDP-1 -d 9
bspc monitor HDMI-1-0 -d 1 2 3 4 5 6 7 8

bspc rule -a Emacs state=tiled
