#!/bin/bash

CONF=$(pwd)/.prettierrc.json

FILE=$(pwd)/$1

if [ ! -f $CONF ]; then
    # if there is no configuration file, we want to just return
    # the current state of the file...
    cat $FILE
    exit 1
fi
prettier --config $CONF $FILE
