#!/bin/bash

read -p 'Node version: ' version
read -p 'Port: ' port

echo Launching docker container for node:$version on port:$port

# spin up docker container with that version
docker run --rm \
           -it \
           -v $PWD:/app \
           -w /app \
           -p $port:3000 \
           node:$version \
           bash
