#!/bin/bash

read -p 'Node version: ' version

echo Launching docker container for node:$version

# spin up docker container with that version
docker run --rm \
           -it \
           -v $PWD:/app \
           -w /app \
           node:$version \
           bash
