(("default"   . ((user-emacs-directory . "~/dot/.emacs.d/")))
 ("spacemacs" . ((user-emacs-directory . "~/.emacs-configs/spacemacs/")))
 ("doom"      . ((user-emacs-directory . "~/.emacs-configs/doom/")))
 ("base"      . ((user-emacs-directory . "~/.emacs-configs/base/")))
 ("vanilla"   . ((user-emacs-directory . "~/.emacs-configs/vanilla/"))))
