;; KEY BINDINGS
(global-set-key (kbd "C-c f d") (lambda ()
                                  (interactive)
                                  (my/open-config-file "init")))

(global-set-key (kbd "C-c f p") (lambda ()
                                  (interactive)
                                  (my/open-config-file "packages")))

(global-set-key (kbd "C-c f u") (lambda ()
                                  (interactive)
                                  (my/open-config-file "gui-packages")))

(global-set-key (kbd "C-c f k") (lambda ()
                                  (interactive)
                                  (my/open-config-file "keys")))

(global-set-key (kbd "C-c f n") (lambda ()
                                  (interactive)
                                  (my/open-config-file "defuns")))

(global-set-key (kbd "C-c f i") 'imenu)
(global-set-key (kbd "C-c t r") 'my/rails-tags)
(global-set-key (kbd "C-c e s") 'eshell)
(global-set-key (kbd "C-x C-c") 'my/quit-emacs)
(global-set-key (kbd "C-o")     'my/new-next-line)
(global-set-key (kbd "C-M-o")   'my/new-previous-line)
(global-set-key (kbd "M-z")     'zap-up-to-char)
(global-set-key (kbd "C-x C-b") 'ibuffer)
(global-set-key (kbd "C-M-\\")  'split-window-right)
(global-set-key (kbd "C-M--")   'split-window-below)
(global-set-key (kbd "C-M-0")   'delete-window)
(global-set-key (kbd "C-M-1")   'delete-other-windows)
(global-set-key (kbd "C-c s r") 'my/send-region-to-shell)
(global-set-key (kbd "C-c s l") 'my/send-line-to-shell)
(global-set-key (kbd "C-M-=")   'balance-windows)
(global-set-key (kbd "C-c i i") 'package-install)
(global-set-key (kbd "C-c i l") 'list-packages)
(global-set-key (kbd "C-c t l") 'display-line-numbers-mode)
(global-set-key (kbd "C-c b r") 'rename-buffer)

(global-set-key (kbd "C-c b v") (lambda ()
                                  (interactive)
                                  (revert-buffer nil t)
                                  (message "Buffer reverted.")))
